version: 2

sources:
  - name: erp
    description: Banco réplica do erp da discorama.
    schema: dbt_jessicappiresss_erp_discorama
    tables:
      - name: rental
        description: Tabela com os dados dos alugueis dos dvds.
        columns:
          - name: rental_id
            description: chave primaria da tabela rental
            tests:
              - unique
              - not_null
                      
      - name: film
        description: Tabela com os dados dos filmes da Discorama.

      - name: payment
        description: Tabela com os dados de pagamentos dos alugueis da Discorama.

      - name: inventory
        description: Tabela com os dados de inventório de cada dvd da discorama.

      - name: film_category
        description: Tabela que relaciona as chaves primárias film_id com category_id.

      - name: category
        description: Tabela com os nomes das categorias dos filmes da Discorama.

